services:
  - type: web
    name: javascript-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      SECURE_TOKEN: "your_secure_token_here" # Replace with your actual token or leave for manual input
    autoDeploy: true
    region: oregon
