services:
  - type: web
    name: javascript-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: SECURE_TOKEN
        sync: false # Prompt for a value in the Render Dashboard
    autoDeploy: true
    region: oregon
